remote_theme: "mmistakes/minimal-mistakes@4.19.1"
minimal_mistakes_skin    :  "neon"

# Site Settings
locale                   : "it-IT"
title                    : "Gianmarco Pepi"
title_separator          : "-"
name                     : "Gianmarco Pepi"
description              : "Data Science and BI student at Università di Pisa"
url                      : https://gianpe.github.io
baseurl                  : ""
repository               : "Gianpe/Gianpe.github.io"
teaser                   : "path/to/your/teaser/image.jpg" # Add a teaser image

# Site Author
author:
  name             : "Gianmarco Pepi"
  avatar           : "laurea.png"
  bio              : "I'm a data science and BI student at Università di Pisa and here you can find my data science projects"
  location         : "Pisa"
  github           : "Gianpe"
  linkedin         : "gianmarco-pepi-982030190"
  # Add any other social links you use

# Analytics
analytics:
  provider         :  "google-universal"
  google:
    tracking_id    : "UA-XXXXXXXXX-X"

# Social Sharing
social:
  type             : "Person"
  name             : "Gianmarco Pepi"
  links:
    - https://github.com/Gianpe
    - https://www.linkedin.com/in/gianmarco-pepi-982030190/
    # Add other social media links here
